### PR TITLE
Fix/legacy tizen jellyseerr media

### LINKED ISSUE #158: [Jellyseerr] Legacy Tizen: TMDB images do not load (text only, no graphics)
### Moonfin version

v2.3.0

### Platform

Tizen (Samsung)

### Platform version

Tizen 3

### TV model

_No response_

### How are you connecting?

Local network (http://IP:5055)

### Using HTTPS?

Yes

### Error message / what happens

On legacy Tizen, Jellyseerr TMDB images do not load at all.
UI shows text labels/titles only, without posters or backdrops.
Probable root cause is HTTPS/TLS certificate validation failure on legacy Tizen trust store / TLS stack when requesting TMDB image hosts.

### Steps to reproduce

Use Samsung Tizen TV/emulator running legacy Tizen (tested on 3.0).
Install and open Moonfin.
Configure Jellyseerr and connect it to a Jellyfin server.
Open any Jellyseerr screen with posters/backdrops (for example Discover, Popular, Trending, or item details).
Wait for image loading to finish.
Observe that text metadata appears, but posters/backdrops do not render (empty/missing graphics).
Expected result:

Posters and backdrops load correctly for Jellyseerr items.
Actual result:

On legacy Tizen, Jellyseerr views show text-only content without graphics.
Notes:

The issue is reproducible on legacy Tizen only.
Likely related to HTTPS/TLS compatibility on old trust stores with external image hosts.

### Does Jellyseerr work from a phone/PC browser on the same network?

Yes

### Logs / extra context (optional)

_No response_

### PR DESCRIPTION
**Pull request by marjac6**
# Pull Request

## Summary
This PR fixes Jellyseerr media loading on legacy Tizen devices, where metadata text is visible but posters/backdrops often fail to load.

The change is intentionally scoped to legacy behavior to minimize risk for newer platforms.

## Related Issues
- Closes #158
- Related to #158

## Type of Change
- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Performance improvement
- [ ] UI/UX update
- [ ] Documentation update
- [ ] Build/CI change
- [ ] Other (describe):

## Changes Made
- Added legacy-scoped image URL normalization for Jellyseerr/TMDB image paths.
- Added legacy protocol fallback for image requests to improve reliability on older TLS/certificate environments.
- Disabled/hid external trailer action on legacy Tizen where this flow is not reliably usable.

## Platform
- [x] Tizen (Samsung)
- [ ] webOS (LG)
- [ ] Both / Shared code

## Testing
- [x] Tested on emulator
- [x] Tested on physical device
- [x] Manual testing completed
- [ ] Not tested (explain why):

### Test Steps
1. Build the legacy Tizen package.
2. Install generated WGT on legacy Tizen emulator and launch app.
3. Open Jellyseerr sections with posters/backdrops (for example Discover/Trending/details).
4. Verify metadata appears and image rendering behavior is correct.

## Screenshots (if applicable)
N/A (compatibility fix, no intentional UI redesign).

## Checklist
- [x] Code builds successfully
- [x] Code follows project style and conventions
- [x] No unnecessary commented-out code
- [ ] No new warnings introduced

### CODE REVIEW

File: packages/app/src/services/jellyseerrApi.js [hunk 1]
```diff
@@ -7,9 +7,17 @@ let moonfinMode = false;
 let jellyfinServerUrl = null;
 let jellyfinAccessToken = null;
 
-// webOS 4's outdated SSL certs can't validate image.tmdb.org over HTTPS,
-// so use HTTP there. Tizen works fine with HTTPS.
-const _useHttp = isWebOS();
+const isLegacyTizen = () => {
```
Comment (RadicalMuffinMan) [inline packages/app/src/services/jellyseerrApi.js]: isLegacyTizen() is duplicated

This exact function is copy-pasted into JellyseerrDetails.js (lines 16-22). Extract it to platform.js as an export alongside the existing isWebOS()/isTizen() and import it in both files.

File: packages/app/src/services/jellyseerrApi.js [hunk 2]
```diff
@@ -7,9 +7,17 @@ let moonfinMode = false;
...
+if (!isTizen() || typeof navigator === 'undefined') return false;
+const match = (navigator.userAgent || '').match(/Tizen\s([0-9]+(?:\.[0-9]+)?)/i);
+if (!match) return true;
+const version = parseFloat(match[1]);
+return Number.isFinite(version) && version <= 3.0;
```
Comment (RadicalMuffinMan) [inline packages/app/src/services/jellyseerrApi.js]: jellyseerrApi.js has:

```
return Number.isFinite(version) && version <= 3.0;
```
JellyseerrDetails.js has:

```
return !Number.isFinite(version) || version <= 3.0;

```
If parseFloat returns NaN, the jellyseerrApi.js copy says "not legacy" (uses HTTPS) while the JellyseerrDetails.js copy says "is legacy" (hides trailer). These should agree. The JellyseerrDetails version (!isFinite || <= 3.0) is the safer default. If you can't determine the version, assume legacy. Use that one in both places.

File: packages/app/src/services/jellyseerrApi.js [hunk 3]
```diff
@@ -7,9 +7,17 @@ let moonfinMode = false;
 let jellyfinServerUrl = null;
 let jellyfinAccessToken = null;
 
-// webOS 4's outdated SSL certs can't validate image.tmdb.org over HTTPS,
-// so use HTTP there. Tizen works fine with HTTPS.
-const _useHttp = isWebOS();
+const isLegacyTizen = () => {
+if (!isTizen() || typeof navigator === 'undefined') return false;
+const match = (navigator.userAgent || '').match(/Tizen\s([0-9]+(?:\.[0-9]+)?)/i);
+if (!match) return true;
```
Comment (RadicalMuffinMan) [inline packages/app/src/services/jellyseerrApi.js]: In jellyseerrApi.js, when regex doesn't match line 13 returns true (is legacy). But then line 15 also does `return Number.isFinite(version) && version <= 3.0` which would never run. This is fine structurally, but combined with the inconsistency above, it's easy to misread. Another reason to deduplicate.

File: packages/app/src/services/jellyseerrApi.js [hunk 4]
```diff
@@ -7,9 +7,17 @@ let moonfinMode = false;
...
+const version = parseFloat(match[1]);
+return Number.isFinite(version) && version <= 3.0;
+};
+
+// webOS 4 and legacy Tizen builds (<=3.0) can fail HTTPS validation for image.tmdb.org,
+// so use HTTP on those devices.
+const shouldUseHttp = () => isWebOS() || isLegacyTizen();
```
Comment (RadicalMuffinMan) [inline packages/app/src/services/jellyseerrApi.js]: shouldUseHttp() is called per-invocation now

The old _useHttp was a module-level constant evaluated once. `shouldUseHttp()` re-evaluates isWebOS() and isLegacyTizen() on every getImageUrl() call. The platform never changes at runtime. Consider caching:
```
const _shouldUseHttp = isWebOS() || isLegacyTizen();
const shouldUseHttp = () => _shouldUseHttp;
```
Or just make it a constant like the original was.

File: packages/app/src/services/jellyseerrApi.js [hunk 5]
```diff
@@ -650,8 +658,38 @@ return getTv(tmdbId);
 
 export const getImageUrl = (path, size = 'w500') => {
 if (!path) return null;
-const proto = _useHttp ? 'http' : 'https';
-return `${proto}://image.tmdb.org/t/p/${size}${path}`;
+const proto = shouldUseHttp() ? 'http' : 'https';
+const normalizedPath = String(path).trim();
```
Comment (RadicalMuffinMan) [inline packages/app/src/services/jellyseerrApi.js:655]: Line 652 already does if (!path) return null;. The only case this second check catches is path being whitespace-only, e.g. " ". Does the Jellyseerr API actually return whitespace-only image paths? If not, this is dead code.

File: packages/app/src/services/jellyseerrApi.js [hunk 6]
```diff
@@ -650,8 +658,38 @@ return getTv(tmdbId);
...
+
+if (!normalizedPath) return null;
+
+// If backend already returns an absolute URL, keep it but normalize protocol
+// for TMDB hosts on legacy devices.
+if (/^https?:\/\//i.test(normalizedPath)) {
```
Comment (RadicalMuffinMan) [inline packages/app/src/services/jellyseerrApi.js]: Two concerns:

Is this path actually observed from the Jellyseerr API? The current code only ever receives relative paths like /abc123.jpg. If this is purely defensive, add a comment noting that. Otherwise it's speculative code that can't be tested.

The new URL() constructor may not be available on the legacy Tizen devices this PR targets (Tizen 2.4 uses an older WebKit much different than tizen 3). The try/catch saves it from crashing, but the protocol normalization silently fails on the exact devices that need it. If you're relying on this path, you need a non-URL fallback (regex replace).

File: packages/app/src/services/jellyseerrApi.js [hunk 7]
```diff
@@ -650,8 +658,38 @@ return getTv(tmdbId);
...
+try {
+const parsed = new URL(normalizedPath);
+const host = parsed.hostname.toLowerCase();
+if (host === 'image.tmdb.org' || host.endsWith('.themoviedb.org')) {
+parsed.protocol = `${proto}:`;
+return parsed.toString();
+}
+return normalizedPath;
```
Comment (RadicalMuffinMan) [inline packages/app/src/services/jellyseerrApi.js]: void e is a lint workaround for unused variables. Use parameterless catch instead:
```
} catch {
    return normalizedPath;
}
```

File: packages/app/src/services/jellyseerrApi.js [hunk 8]
```diff
@@ -650,8 +658,38 @@ return getTv(tmdbId);
...
+} catch (e) {
+void e;
+return normalizedPath;
+}
+}
+
+if (normalizedPath.startsWith('//')) {
```
Comment (RadicalMuffinMan) [inline packages/app/src/services/jellyseerrApi.js]: Same question: does the Jellyseerr API ever return protocol-relative paths? If not, this is dead code

File: packages/app/src/views/JellyseerrDetails/JellyseerrDetails.js [hunk 9]
```diff
@@ -674,6 +683,7 @@ const CancelRequestPopup = memo(({open, pendingRequests, title, onConfirm, onClo
 
 const JellyseerrDetails = ({mediaType, mediaId, onClose, onSelectItem, onPlayInMoonfin, onSelectPerson, onSelectKeyword, onBack, backHandlerRef}) => {
 	const {isAuthenticated, user: contextUser} = useJellyseerr();
+	const supportsExternalTrailerSearch = !isLegacyTizen();
```
Comment (RadicalMuffinMan) [inline packages/app/src/views/JellyseerrDetails/JellyseerrDetails.js]: This is inside the component body, so it runs on every render. The platform never changes. Either:

- Make it a module-level constant above the component: const supportsExternalTrailerSearch = !isLegacyTizen();
- Or memoize: const supportsExternalTrailerSearch = useMemo(() => !isLegacyTizen(), []);

Module-level constant is simplest.

File: packages/app/src/views/JellyseerrDetails/JellyseerrDetails.js [hunk 10]
```diff
@@ -991,12 +1001,13 @@ const JellyseerrDetails = ({mediaType, mediaId, onClose, onSelectItem, onPlayInM
 	}, [pendingRequests, mediaId, mediaType]);
 
 	const handleTrailer = useCallback(() => {
+		if (!supportsExternalTrailerSearch) return;
```
Comment (RadicalMuffinMan) [inline packages/app/src/views/JellyseerrDetails/JellyseerrDetails.js]: The button that calls this handler is already conditionally rendered on line 1363

File: packages/app/src/views/JellyseerrDetails/JellyseerrDetails.js [hunk 11]
```diff
@@ -991,12 +1001,13 @@ const JellyseerrDetails = ({mediaType, mediaId, onClose, onSelectItem, onPlayInM
...
 		const mediaTitle = details?.title || details?.name || 'Unknown';
 		const mediaYear = details?.releaseDate?.substring(0, 4) || details?.firstAirDate?.substring(0, 4) || '';
 		const searchQuery = `${mediaTitle} ${mediaYear} official trailer`;
 		const youtubeUrl = `https://www.youtube.com/results?search_query=${encodeURIComponent(searchQuery)}`;
 		window.open(youtubeUrl, '_blank');
-	}, [details]);
+	}, [details, supportsExternalTrailerSearch]);
```
Comment (RadicalMuffinMan) [inline packages/app/src/views/JellyseerrDetails/JellyseerrDetails.js]: If you remove the early return above, supportsExternalTrailerSearch doesn't need to be in the dependency array. And even if you keep it, it's a value that never changes, so it shouldn't trigger re-creation of the callback.

**Review by RadicalMuffinMan — CHANGES_REQUESTED** [review]

File: packages/app/src/services/jellyseerrApi.js (hunk 1 above)
Comment (marjac6) [reply packages/app/src/services/jellyseerrApi.js]: Agree, moved function to platform.js

File: packages/app/src/services/jellyseerrApi.js (hunk 2 above)
Comment (marjac6) [reply packages/app/src/services/jellyseerrApi.js]: Used (!isFinite || <= 3.0) logic

File: packages/app/src/services/jellyseerrApi.js (hunk 4 above)
Comment (marjac6) [reply packages/app/src/services/jellyseerrApi.js]: Corrected to constant value

File: packages/app/src/services/jellyseerrApi.js (hunk 5 above)
Comment (marjac6) [reply packages/app/src/services/jellyseerrApi.js:655]: Jellyseerr API should not return whitespace paths, deleted unnecesary code

File: packages/app/src/services/jellyseerrApi.js (hunk 6 above)
Comment (marjac6) [reply packages/app/src/services/jellyseerrApi.js]: It was purely defensive. Tested. Code unnecesary.

File: packages/app/src/services/jellyseerrApi.js (hunk 7 above)
Comment (marjac6) [reply packages/app/src/services/jellyseerrApi.js]: Fragment deleted with unnecesary absolute URL checking

File: packages/app/src/services/jellyseerrApi.js (hunk 8 above)
Comment (marjac6) [reply packages/app/src/services/jellyseerrApi.js]: OK

File: packages/app/src/views/JellyseerrDetails/JellyseerrDetails.js (hunk 11 above)
Comment (marjac6) [reply packages/app/src/views/JellyseerrDetails/JellyseerrDetails.js]: Removed from dependency array.

File: packages/app/src/views/JellyseerrDetails/JellyseerrDetails.js (hunk 9 above)
Comment (marjac6) [reply packages/app/src/views/JellyseerrDetails/JellyseerrDetails.js]: Moved to module-level constant

File: packages/app/src/views/JellyseerrDetails/JellyseerrDetails.js (hunk 10 above)
Comment (marjac6) [reply packages/app/src/views/JellyseerrDetails/JellyseerrDetails.js]: Deleted if

**Comment by marjac6** [comment]
Addressed all requested changes in latest commit: 233e331
